// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOPServer.Repository.DBContext;

#nullable disable

namespace SOPServer.Repository.Migrations
{
    [DbContext(typeof(SOPServerContext))]
    [Migration("20251106145802_MakeItemFieldsNullable")]
    partial class MakeItemFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Outfit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSaved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Outfit__3214EC07");

                    b.HasIndex("UserId");

                    b.ToTable("Outfit", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.AISetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AISettings", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC071F17A97B");

                    b.HasIndex("ParentId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.CommentPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ParentCommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__CommentPost__3214EC07");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentPost", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Follower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FollowerId")
                        .HasColumnType("bigint");

                    b.Property<long>("FollowingId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Follower__3214EC07");

                    b.HasIndex("FollowingId");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Follower_FollowerId_FollowingId");

                    b.ToTable("Follower", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Hashtag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Hashtag__3214EC07");

                    b.ToTable("Hashtag", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AiDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Color")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fabric")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FrequencyWorn")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastWornAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeatherSuitable")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Item__3214EC0747906DDA");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemOccasion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OccasionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemOcca__3214EC0770686AD7");

                    b.HasIndex("ItemId");

                    b.HasIndex("OccasionId");

                    b.ToTable("ItemOccasion", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemSeas__3214EC07D4095C08");

                    b.HasIndex("ItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("ItemSeason", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StyleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemStyl__3214EC07C65FA98C");

                    b.HasIndex("ItemId");

                    b.HasIndex("StyleId");

                    b.ToTable("ItemStyle", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Job__3214EC07BB559D15");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.LikePost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__LikePost__3214EC07");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_LikePost_PostId_UserId");

                    b.ToTable("LikePost", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Occasion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Occasion__3214EC07770E08E7");

                    b.ToTable("Occasion", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.OutfitItems", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OutfitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__OutfitIt__3214EC07");

                    b.HasIndex("ItemId");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitItems", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.OutfitUsageHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUsed")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("OutfitId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserOccassionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__OutfitUs__3214EC07");

                    b.HasIndex("OutfitId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserOccassionId");

                    b.ToTable("OutfitUsageHistory", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Post__3214EC07");

                    b.HasIndex("UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.PostHashtags", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("HashtagId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__PostHash__3214EC07");

                    b.HasIndex("HashtagId");

                    b.HasIndex("PostId");

                    b.ToTable("PostHashtags", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.PostImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__PostImag__3214EC07");

                    b.HasIndex("PostId");

                    b.ToTable("PostImage", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Season__3214EC07455A7347");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Style", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Style__3214EC074BD205BF");

                    b.ToTable("Style", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvoidedColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvtUrl")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFirstTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLoginWithGoogle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerifiedEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreferedColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0767F70699");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105340DE61212")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserOccasion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOccasion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("OccasionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeatherSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__UserOcca__3214EC07");

                    b.HasIndex("OccasionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOccasion", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("StyleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__UserStyl__3214EC07CE37713F");

                    b.HasIndex("StyleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStyle", (string)null);
                });

            modelBuilder.Entity("Outfit", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("Outfits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Outfit_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Category_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.CommentPost", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.CommentPost", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_CommentPost_ParentComment");

                    b.HasOne("SOPServer.Repository.Entities.Post", "Post")
                        .WithMany("CommentPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CommentPost_Post");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("CommentPosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_CommentPost_User");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Follower", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.User", "FollowerUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Follower_FollowerUser");

                    b.HasOne("SOPServer.Repository.Entities.User", "FollowingUser")
                        .WithMany("Following")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Follower_FollowingUser");

                    b.Navigation("FollowerUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Item_Category");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Item_User");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemOccasion", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemOccasions")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemOccasion_Item");

                    b.HasOne("SOPServer.Repository.Entities.Occasion", "Occasion")
                        .WithMany("ItemOccasions")
                        .HasForeignKey("OccasionId")
                        .HasConstraintName("FK_ItemOccasion_Occasion");

                    b.Navigation("Item");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemSeason", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemSeasons")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemSeason_Item");

                    b.HasOne("SOPServer.Repository.Entities.Season", "Season")
                        .WithMany("ItemSeasons")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK_ItemSeason_Season");

                    b.Navigation("Item");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemStyle", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemStyles")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemStyle_Item");

                    b.HasOne("SOPServer.Repository.Entities.Style", "Style")
                        .WithMany("ItemStyles")
                        .HasForeignKey("StyleId")
                        .HasConstraintName("FK_ItemStyle_Style");

                    b.Navigation("Item");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.LikePost", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Post", "Post")
                        .WithMany("LikePosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LikePost_Post");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("LikePosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LikePost_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.OutfitItems", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("OutfitItems")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_OutfitItems_Item");

                    b.HasOne("Outfit", "Outfit")
                        .WithMany("OutfitItems")
                        .HasForeignKey("OutfitId")
                        .HasConstraintName("FK_OutfitItems_Outfit");

                    b.Navigation("Item");

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.OutfitUsageHistory", b =>
                {
                    b.HasOne("Outfit", "Outfit")
                        .WithMany("OutfitUsageHistories")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OutfitUsageHistory_Outfit");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("OutfitUsageHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_OutfitUsageHistory_User");

                    b.HasOne("SOPServer.Repository.Entities.UserOccasion", "UserOccasion")
                        .WithMany("OutfitUsageHistories")
                        .HasForeignKey("UserOccassionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_OutfitUsageHistory_UserOccasion");

                    b.Navigation("Outfit");

                    b.Navigation("User");

                    b.Navigation("UserOccasion");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Post", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Post_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.PostHashtags", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Hashtag", "Hashtag")
                        .WithMany("PostHashtags")
                        .HasForeignKey("HashtagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostHashtags_Hashtag");

                    b.HasOne("SOPServer.Repository.Entities.Post", "Post")
                        .WithMany("PostHashtags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostHashtags_Post");

                    b.Navigation("Hashtag");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.PostImage", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Post", "Post")
                        .WithMany("PostImages")
                        .HasForeignKey("PostId")
                        .HasConstraintName("FK_PostImage_Post");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_User_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserOccasion", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Occasion", "Occasion")
                        .WithMany("UserOccasions")
                        .HasForeignKey("OccasionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_UserOccasion_Occasion");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("UserOccasions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserOccasion_User");

                    b.Navigation("Occasion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserStyle", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Style", "Style")
                        .WithMany("UserStyles")
                        .HasForeignKey("StyleId")
                        .HasConstraintName("FK_UserStyle_Style");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("UserStyles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserStyle_User");

                    b.Navigation("Style");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Outfit", b =>
                {
                    b.Navigation("OutfitItems");

                    b.Navigation("OutfitUsageHistories");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.CommentPost", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Hashtag", b =>
                {
                    b.Navigation("PostHashtags");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.Navigation("ItemOccasions");

                    b.Navigation("ItemSeasons");

                    b.Navigation("ItemStyles");

                    b.Navigation("OutfitItems");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Job", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Occasion", b =>
                {
                    b.Navigation("ItemOccasions");

                    b.Navigation("UserOccasions");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Post", b =>
                {
                    b.Navigation("CommentPosts");

                    b.Navigation("LikePosts");

                    b.Navigation("PostHashtags");

                    b.Navigation("PostImages");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Season", b =>
                {
                    b.Navigation("ItemSeasons");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Style", b =>
                {
                    b.Navigation("ItemStyles");

                    b.Navigation("UserStyles");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.Navigation("CommentPosts");

                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Items");

                    b.Navigation("LikePosts");

                    b.Navigation("OutfitUsageHistories");

                    b.Navigation("Outfits");

                    b.Navigation("Posts");

                    b.Navigation("UserOccasions");

                    b.Navigation("UserStyles");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserOccasion", b =>
                {
                    b.Navigation("OutfitUsageHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
