// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOPServer.Repository.DBContext;

#nullable disable

namespace SOPServer.Repository.Migrations
{
    [DbContext(typeof(SOPServerContext))]
    partial class SOPServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Category__3214EC071F17A97B");

                    b.HasIndex("ParentId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Goal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Goal__3214EC07C1B22C27");

                    b.ToTable("Goal", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AiDescription")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Color")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Condition")
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fabric")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FrequencyWorn")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImgUrl")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastWornAt")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pattern")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Tag")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("WeatherSuitable")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Item__3214EC0747906DDA");

                    b.HasIndex("UserId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemGoal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("GoalId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemGoal__3214EC07628E8E1B");

                    b.HasIndex("GoalId");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemGoal", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemOccasion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OccasionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemOcca__3214EC0770686AD7");

                    b.HasIndex("ItemId");

                    b.HasIndex("OccasionId");

                    b.ToTable("ItemOccasion", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SeasonId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemSeas__3214EC07D4095C08");

                    b.HasIndex("ItemId");

                    b.HasIndex("SeasonId");

                    b.ToTable("ItemSeason", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("StyleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__ItemStyl__3214EC07C65FA98C");

                    b.HasIndex("ItemId");

                    b.HasIndex("StyleId");

                    b.ToTable("ItemStyle", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Job__3214EC07BB559D15");

                    b.ToTable("Job", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Occasion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Occasion__3214EC07770E08E7");

                    b.ToTable("Occasion", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Season", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Season__3214EC07455A7347");

                    b.ToTable("Season", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Style", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Style__3214EC074BD205BF");

                    b.ToTable("Style", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AvoidedColor")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvtUrl")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsStylist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsVerifiedEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("JobId")
                        .HasColumnType("bigint");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PreferedColor")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0767F70699");

                    b.HasIndex("JobId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105340DE61212")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserStyle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("StyleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__UserStyl__3214EC07CE37713F");

                    b.HasIndex("StyleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserStyle", (string)null);
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Category", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Category_Parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Item_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemGoal", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Goal", "Goal")
                        .WithMany("ItemGoals")
                        .HasForeignKey("GoalId")
                        .HasConstraintName("FK_ItemGoal_Goal");

                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemGoals")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemGoal_Item");

                    b.Navigation("Goal");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemOccasion", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemOccasions")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemOccasion_Item");

                    b.HasOne("SOPServer.Repository.Entities.Occasion", "Occasion")
                        .WithMany("ItemOccasions")
                        .HasForeignKey("OccasionId")
                        .HasConstraintName("FK_ItemOccasion_Occasion");

                    b.Navigation("Item");

                    b.Navigation("Occasion");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemSeason", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemSeasons")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemSeason_Item");

                    b.HasOne("SOPServer.Repository.Entities.Season", "Season")
                        .WithMany("ItemSeasons")
                        .HasForeignKey("SeasonId")
                        .HasConstraintName("FK_ItemSeason_Season");

                    b.Navigation("Item");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.ItemStyle", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Item", "Item")
                        .WithMany("ItemStyles")
                        .HasForeignKey("ItemId")
                        .HasConstraintName("FK_ItemStyle_Item");

                    b.HasOne("SOPServer.Repository.Entities.Style", "Style")
                        .WithMany("ItemStyles")
                        .HasForeignKey("StyleId")
                        .HasConstraintName("FK_ItemStyle_Style");

                    b.Navigation("Item");

                    b.Navigation("Style");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Job", "Job")
                        .WithMany("Users")
                        .HasForeignKey("JobId")
                        .HasConstraintName("FK_User_Job");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.UserStyle", b =>
                {
                    b.HasOne("SOPServer.Repository.Entities.Style", "Style")
                        .WithMany("UserStyles")
                        .HasForeignKey("StyleId")
                        .HasConstraintName("FK_UserStyle_Style");

                    b.HasOne("SOPServer.Repository.Entities.User", "User")
                        .WithMany("UserStyles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserStyle_User");

                    b.Navigation("Style");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Category", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Goal", b =>
                {
                    b.Navigation("ItemGoals");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Item", b =>
                {
                    b.Navigation("ItemGoals");

                    b.Navigation("ItemOccasions");

                    b.Navigation("ItemSeasons");

                    b.Navigation("ItemStyles");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Job", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Occasion", b =>
                {
                    b.Navigation("ItemOccasions");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Season", b =>
                {
                    b.Navigation("ItemSeasons");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.Style", b =>
                {
                    b.Navigation("ItemStyles");

                    b.Navigation("UserStyles");
                });

            modelBuilder.Entity("SOPServer.Repository.Entities.User", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("UserStyles");
                });
#pragma warning restore 612, 618
        }
    }
}
