// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class Goal : BaseEntity
{
    public string Name { get; set; }

    public virtual ICollection<ItemGoal> ItemGoals { get; set; } = new List<ItemGoal>();
}