// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class ItemSeason : BaseEntity
{
    public long? ItemId { get; set; }

    public long? SeasonId { get; set; }

    public virtual Item Item { get; set; }

    public virtual Season Season { get; set; }
}