// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class Item : BaseEntity
{
    public string Name { get; set; }

    public long? UserId { get; set; }

    public long? CategoryId { get; set; }

    public string? Color { get; set; }

    public string? AiDescription { get; set; }

    public string? Brand { get; set; }

    public string? FrequencyWorn { get; set; }

    public DateTime? LastWornAt { get; set; }

    public string ImgUrl { get; set; }

    public string? WeatherSuitable { get; set; }

    public string? Condition { get; set; }

    public string? Pattern { get; set; }

    public string? Fabric { get; set; }

    public bool? IsAnalyzed { get; set; }

    public int? AIConfidence { get; set; }
    public string? AIAnalyzeJson { get; set; }

    public virtual ICollection<ItemOccasion> ItemOccasions { get; set; } = new List<ItemOccasion>();

    public virtual ICollection<ItemSeason> ItemSeasons { get; set; } = new List<ItemSeason>();

    public virtual ICollection<ItemStyle> ItemStyles { get; set; } = new List<ItemStyle>();
    public virtual ICollection<OutfitItems> OutfitItems { get; set; } = new List<OutfitItems>();
    public virtual User User { get; set; }
    public virtual Category Category { get; set; }
}