// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class ItemStyle : BaseEntity
{
    public long? ItemId { get; set; }

    public long? StyleId { get; set; }

    public virtual Item Item { get; set; }

    public virtual Style Style { get; set; }
}