// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace SOPServer.Repository.Entities;

public partial class ItemWornAtHistory : BaseEntity
{
    public long ItemId { get; set; }

    public DateTime WornAt { get; set; }

    public virtual Item Item { get; set; }
}
