// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SOPServer.Repository.Enums;
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class Job : BaseEntity
{
    public string Name { get; set; }

    public string Description { get; set; }

    public string? Other { get; set; }

    public CreatedBy CreatedBy { get; set; } = CreatedBy.SYSTEM;

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}