// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class Occasion : BaseEntity
{
    public string Name { get; set; }

    public virtual ICollection<ItemOccasion> ItemOccasions { get; set; } = new List<ItemOccasion>();
}