// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class Season : BaseEntity
{
    public string Name { get; set; }

    public virtual ICollection<ItemSeason> ItemSeasons { get; set; } = new List<ItemSeason>();
}