// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SOPServer.Repository.Enums;
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class User : BaseEntity
{
    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public Role Role { get; set; }

    public string DisplayName { get; set; }

    public bool? IsVerifiedEmail { get; set; }

    public bool? IsStylist { get; set; }

    public bool? IsPremium { get; set; }

    public string AvtUrl { get; set; }

    public DateOnly? Dob { get; set; }

    public Gender Gender { get; set; }

    public string PreferedColor { get; set; }

    public string AvoidedColor { get; set; }

    public string Location { get; set; }

    public string Bio { get; set; }

    public long? JobId { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual Job Job { get; set; }

    public virtual ICollection<UserStyle> UserStyles { get; set; } = new List<UserStyle>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}