// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using SOPServer.Repository.Enums;
using System;
using System.Collections.Generic;

namespace SOPServer.Repository.Entities;

public partial class User : BaseEntity
{
    public string Email { get; set; }

    public string? PasswordHash { get; set; }

    public Role Role { get; set; }

    public string DisplayName { get; set; }

    public bool IsVerifiedEmail { get; set; } = false;

    public bool IsPremium { get; set; } = false;

    public bool IsLoginWithGoogle { get; set; } = false;

    public bool? IsFirstTime { get; set; }

    public string? AvtUrl { get; set; }

    public DateOnly? Dob { get; set; }

    public Gender Gender { get; set; }

    public List<string>? PreferedColor { get; set; }

    public List<string>? AvoidedColor { get; set; }

    public string? Location { get; set; }

    public string? Bio { get; set; }

    public long? JobId { get; set; }

    public virtual ICollection<Item> Items { get; set; } = new List<Item>();

    public virtual Job Job { get; set; }

    public virtual ICollection<UserStyle> UserStyles { get; set; } = new List<UserStyle>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Outfit> Outfits { get; set; } = new List<Outfit>();

    public virtual ICollection<OutfitUsageHistory> OutfitUsageHistories { get; set; } = new List<OutfitUsageHistory>();

    public virtual ICollection<UserOccasion> UserOccasions { get; set; } = new List<UserOccasion>();

    public virtual ICollection<LikePost> LikePosts { get; set; } = new List<LikePost>();

    public virtual ICollection<CommentPost> CommentPosts { get; set; } = new List<CommentPost>();

    public virtual ICollection<Follower> Followers { get; set; } = new List<Follower>();

    public virtual ICollection<Follower> Following { get; set; } = new List<Follower>();
}