using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SOPServer.Service.BusinessModels.VirtualTryOnModels
{
    /// <summary>
    /// Request model for batch virtual try-on feature
    /// </summary>
    public class BatchVirtualTryOnRequest
    {
        /// <summary>
        /// List of try-on items to process
        /// </summary>
        /// <example>[{"uuid": 1, "human_image_url": "https://example.com/human1.jpg", "clothing_urls": ["https://example.com/item1.jpg"]}]</example>
        [Required(ErrorMessage = "Items list is required")]
        [MinLength(1, ErrorMessage = "At least one item is required")]
        [JsonPropertyName("items")]
        public List<BatchTryOnItem> Items { get; set; } = new List<BatchTryOnItem>();
    }

    /// <summary>
    /// Individual try-on item in the batch request
    /// </summary>
    public class BatchTryOnItem
    {
        /// <summary>
        /// Unique identifier generated by frontend
        /// </summary>
        /// <example>1</example>
        [Required(ErrorMessage = "UUID is required")]
        [JsonPropertyName("uuid")]
        public int Uuid { get; set; }

        /// <summary>
        /// URL of the human image
        /// </summary>
        /// <example>https://example.com/human.jpg</example>
        [Required(ErrorMessage = "Human image URL is required")]
        [JsonPropertyName("human_image_url")]
        public string HumanImageUrl { get; set; } = string.Empty;

        /// <summary>
        /// List of clothing item image URLs to apply
        /// </summary>
        /// <example>["https://example.com/item1.jpg", "https://example.com/item2.jpg"]</example>
        [Required(ErrorMessage = "At least one clothing URL is required")]
        [MinLength(1, ErrorMessage = "At least one clothing URL is required")]
        [JsonPropertyName("clothing_urls")]
        public List<string> ClothingUrls { get; set; } = new List<string>();
    }
}
